package com.ecommerce.product.model;

import jakarta.persistence.*;

import java.math.BigDecimal;

/**
 * JPA entity representing a product in the catalogue.
 *
 * <p>Persisted in the PostgreSQL {@code products} table. The schema is
 * generated by Hibernate on startup ({@code ddl-auto: create-drop}).
 * Sample rows are inserted by {@link com.ecommerce.product.ProductDataInitializer}
 * when the table is empty.</p>
 *
 * <p>Note: stock deduction is not performed by this service — the
 * {@code stock} field represents the seeded/initial quantity and is used
 * by {@code order-service} for availability checks only.</p>
 */
@Entity
@Table(name = "products")
public class Product {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(nullable = false)
    private String name;

    private String description;

    @Column(nullable = false)
    private BigDecimal price;

    @Column(nullable = false)
    private Integer stock;

    protected Product() {
        // JPA
    }

    public Product(String name, String description, BigDecimal price, Integer stock) {
        this.name = name;
        this.description = description;
        this.price = price;
        this.stock = stock;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public BigDecimal getPrice() {
        return price;
    }

    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    public Integer getStock() {
        return stock;
    }

    public void setStock(Integer stock) {
        this.stock = stock;
    }
}

