server:
  port: 8761

spring:
  application:
    name: eureka-server

eureka:
  client:
    register-with-eureka: false   # el propio eureka no se registra a sí mismo
    fetch-registry: false
  server:
    wait-time-in-ms-between-sync-retries: 3000